package service;

public enum RequestCode {
    INVALID_LOGIN_OR_PASSWORD,
    ERROR_DATA_BASE,
    SERVER_OFFLINE,
    REGISTRATION_SUCCESSFUL,
    EMAIL_ALREADY_EXISTS,
    SING_IN_SUCCESSFUL,
    OPERATION_ERROR,
    OPERATION_SUCCESSFUL,
    ADD_IMAGE_SUCCESSFUL
}
